### PR TITLE
Added GetAllValidBooks() method

### LINKED ISSUE #36: a BookDB method to get all valid books

### PR DESCRIPTION
**Pull request by TungKimProgrammer**
Closes #36

### CODE REVIEW

**Comment by crex424** [comment]
Mind if I ask what this method will be used for?

**Comment by TungKimProgrammer** [comment]
In the database we might have books with invalid isbn. In the Book Combo box, for registration purpose, we just want to list all books with valid isbn.
In Book Managing form, we display all books regardless the validity of books so we could update/delete.

**Comment by crex424** [comment]
Oh ok, that makes sense. go ahead and merge.

**Comment by TungKimProgrammer** [comment]
@crex424 speaking of valid books. I think you might need to adjust the code for Book combo box on main form.

**Pull request merged**
