### PR TITLE
Created customer class

### LINKED ISSUE #2: Create a Customers Class
Create a Customers Class with:
Constructor(s):
- [x] A constructor with parameters title, fName, lName, dob(Date of Birth)

Properties:
- [x] The customers ID
- [x] The customers title (Mr, Mrs, Dr)
- [x] The customers legal First Name
- [x] The customers legal Last Name
- [x] The customers legal Date of Birth

Methods:
- [x] A method that formats the customers full name (ex. Last name, First name)
- [x] A ToString override method that formats the customers Details (ex. Dr. LastName, FirstName 09/22/1999)

### PR DESCRIPTION
**Pull request by crex424**
Closes #2

### CODE REVIEW

**Comment by TungKimProgrammer** [comment]
I downloaded this repository to my computer but I don't see Customer Class in my VS. I guess I would be able to see it after you merged the pull request.
I am working on issue #1 Create a Book Class and see what's going on.

**Comment by TungKimProgrammer** [comment]
Hi Campbell,
I am creating Book class and something came up.
I've read this link, it's about the order of items within a class:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md
Do you think we should follow how they put items within a class?

**Comment by crex424** [comment]
Hi Tung,
I think that is a great idea. Looks nice and will add some formality to the chaos.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by crex424** [comment]
Hello Tung,
Could you do a quick check through my pull request to see if there is anything you might want me to change before I merge it with the master branch.
Please and thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TungKimProgrammer** [comment]
Your code looks good to me.
Just one little thing, if we agree that we should use the formality, do you think moving the constructor on top of properties is gonna make it look better?
Other than that, you can merge the pull request.
Thank you very much!

**Comment by TungKimProgrammer** [comment]
After Sync, I can see Customer class now. Great Experience!

**Pull request merged**
