### PR TITLE
Created Validation class with basic validation methods

### LINKED ISSUE #9: Create Validator Class
Create Validator Class with:
Methods:
- [x] IsPresent method with TextBox parameter to check if text is present. Returns true or false
- [x] IsValidDate method with string parameter to check if date is a valid date . Returns true or false
- [x] IsValidISBN with ISBN parameter to check if ISBN is valid. Returns true or false
- [x] IsDigitsOnly method with string parameter to check if string is all digits. Returns true or false
- [x] RemoveAllWhiteSpaces method with string parameter which returns the string with whitespace removed

### PR DESCRIPTION
**Pull request by crex424**
Closes #9

### CODE REVIEW

**Comment by TungKimProgrammer** [comment]
Hi Campbell,
In method RemoveAllWhiteSpaces(string), besides removing leading and trailing white-space characters, you you think we should remove all internal white spaces as well? 
Users are allowed to type dashes, but we should remove them. Should we include the dash removal within a method in Validator or we could do it while working with the inserting?

We can do it as below if you want to:

// remove any spaces within the string
input = Regex.Replace(input, " ", "");

// remove any dashes within the isbn
isbn = Regex.Replace(isbn, "-", "");

**Comment by crex424** [comment]
I think that is a great idea. Should definitely help with working with data much easier.

**Comment by crex424** [comment]
Though if we are adding that many more methods. Maybe we should create a new class to put removeWhiteSpace and the rest of them. The class could be named FormatData or something similar.

**Comment by crex424** [comment]
Let me know what you think of this suggestion.

**Comment by TungKimProgrammer** [comment]
Yes, I think that would be a great idea since we will have to use them multiple times such as validating and for the inserting to the database and validating again when user wants to update something. I suggest we leave this issue open until we finish the extra class and implement new method to make this class better, what do you think?

**Comment by crex424** [comment]
Sounds good.

**Pull request merged**
