### PR TITLE
Created and added format the main form

### LINKED ISSUE #4: Re-Created Main Windows Form
Format the Main form with:
- [x] Form labels
- [x] Combo boxes for Customers, books
- [x] Date picker for date
- [x] Buttons for Register Book, Manage Customers, Manage Books, and Manage Registrations
- [x] Tab order/index and 
- [x] Access Keys to make it easier to navigate

### PR DESCRIPTION
**Pull request by TungKimProgrammer**
Closes #4

### CODE REVIEW

**Comment by TungKimProgrammer** [comment]
For the Windows Form, how we can really take a visual look at partner's work while it has not been merged? 
image

**Comment by crex424** [comment]
Besides the screen shot of the forms looks that you have already provided. The only other thing I can think of at the moment would be screen sharing while in a zoom call or something similar.

**Comment by TungKimProgrammer** [comment]
I just watched the panopto recording for CPW 211 lab (Feb 1), Joe mentioned about checking out a partner's branch (remote branch) while the pull request's still open. the time stamp is around 5:00 of the recording. I think we can try that to check out each other's work in stead of reading our code on GitHub.

**Comment by TungKimProgrammer** [comment]
Have you been able to check out my branch for this pull request on your end? Do you think I can merge this pull request?

**Comment by crex424** [comment]
Looks really good, go ahead and merge.

**Comment by TungKimProgrammer** [comment]
For some reason, after I merged this Pull Request and synced with my computer, when I ran the Form, it returns blank.
Would you please try on your end to see any differences?
Thank you!

**Comment by crex424** [comment]
Hello @TungKimProgrammer 
The form on my side is also blank. A very odd problem we seem to be having here.

**Pull request merged**
